---
- name:  install | required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: required_packages

- name:  install | create directory
  file:
    path: /opt/venv/
    state: directory
    mode: 0755

- name:  install | get tarball
  get_url:
    url: "{{ virtualenv_url }}/{{ item }}.tar.gz"
    dest: "/tmp/{{ item }}.tar.gz"
  with_items: monasca_tarball

- name:  install | unarchive
  shell: "tar -xzvf /tmp/{{ item }}.tar.gz"
  args:
    chdir: /opt/venv
    creates: "/opt/venv/{{ item.split('.')[0] }}"
  with_items: monasca_tarball
